language: swift

osx_image: xcode10.2

script:
  - xcodebuild test -enableCodeCoverage YES -scheme MPVPN-Example -workspace Example/MPVPN.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=12.2'
